services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 64-backend
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      # - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:VjoO86vMLsiKGZXTZvQLQKjKvJyvOL1TrEcM1W4XRaA=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=backend
      - DB_USERNAME=backend_root
      - DB_PASSWORD=backend_docker
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: backend-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: backend_root
      MYSQL_PASSWORD: backend_docker
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
